name: "S3 Deploy"
description: "S3 Deploy for github workflow"
inputs:
  public-root:
    description: "Public Root Directory to Deploy"
    required: true
    default: "./dist"
  region:
    description: "AWS Region of S3 Bucket"
    required: true
    default: "us-east-1"
  bucket:
    description: "Name of S3 Bucket"
    required: true
  distribution-id:
    description: "Invalidtion Id for Cloudfront. It will not invoked if not exist"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
